### ISSUE TITLE
Closing a detail feature doesn't go back correctly 

### ISSUE THREAD

**Issue by herau** [jenkinsci/blueocean-plugin#208]
* Go to a pipeline job
* Select any items in the activity tab
* Select any tab from "Changes" / "tests" or "Artifacts" 
* Close the panel (escape or click)

You are not going back to the item of the pipelines.

![screen shot 2016-05-27 at 2 13 19 pm](https://cloud.githubusercontent.com/assets/2950666/15607706/3b8ec5d6-2415-11e6-8f21-e3cfa3e03573.png)
![screen shot 2016-05-27 at 2 13 02 pm](https://cloud.githubusercontent.com/assets/2950666/15607708/3da4ae62-2415-11e6-8998-7b6a4a67c503.png)

> Tests with the master branch

**Comment by daniel-beck** [comment]
@herau Disabling *Issues* support in this repository as per @michaelneale's request.

Please file an issue in JIRA: https://wiki.jenkins-ci.org/display/JENKINS/How+to+report+an+issue
