### ISSUE TITLE
The "New Pipeline" link is hard-coded to `/jenkins/view/All/newJob`

### ISSUE THREAD

**Issue by ericcitaire** [jenkinsci/blueocean-plugin#209]
in [`blueocean-dashboard/src/main/js/components/Pipelines.jsx`](https://github.com/cloudbees/blueocean/blob/24c104c4cf35d542eddca336fbbcd6a691a17439/blueocean-dashboard/src/main/js/components/Pipelines.jsx#L41), the link to the job creation is hard-coded to `/jenkins/view/All/newJob`, which is an issue when Jenkins is not installed in `/jenkins`.

**Comment by daniel-beck** [comment]
@ericcitaire Disabling *Issues* support in this repository as per @michaelneale's request.

Please file an issue in JIRA: https://wiki.jenkins-ci.org/display/JENKINS/How+to+report+an+issue
