### ISSUE TITLE
Build log displays HTML markup in Firefox

### ISSUE THREAD

**Issue by ericcitaire** [jenkinsci/blueocean-plugin#210]
Firefox 46.0.1
Ubuntu 16.04

Here's a [screenshot](http://postimg.org/image/5xzrenw57/).

**Comment by daniel-beck** [comment]
@ericcitaire Disabling *Issues* support in this repository as per @michaelneale's request.

Please file an issue in JIRA: https://wiki.jenkins-ci.org/display/JENKINS/How+to+report+an+issue
